name: actionsBuildApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'temurin'

jobs:

  jobBuildApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - run: ./gradlew wrapper --gradle-version latest --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Gradle wrapper

      - run: ./gradlew ktlintFormat --stacktrace
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Ktlint format

      - run: ./gradlew assembleDebug assembleRelease --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release
