name: actionsBuildApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21

jobs:

  jobBuildApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew ktlintFormat assembleDebug assembleRelease --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release

      - run: ./gradlew wrapper --gradle-version latest --stacktrace

      - uses: stefanzweifel/git-auto-commit-action@v5
