name: actionsBuildApp

on: [ push ]

env:
  JAVA_VERSION: 21

jobs:

  jobBuildApp:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        if: ${{ matrix.os != 'self-hosted' }}
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assembleDebug assembleRelease --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release
